# Generated by Django 6.0 on 2025-12-12 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('content', models.TextField()),
                ('is_definition', models.BooleanField(default=False)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='pdf_manager.uploadedpdf')),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedDiagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='diagrams/')),
                ('page_number', models.IntegerField()),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagrams', to='pdf_manager.uploadedpdf')),
            ],
        ),
    ]
