# Generated by Django 6.0 on 2026-01-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_manager', '0002_uploadedpdf_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracteddiagram',
            name='image_hash',
            field=models.CharField(db_index=True, default='legacy', help_text='MD5 hash of image bytes for deduplication', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extractedtext',
            name='content_hash',
            field=models.CharField(db_index=True, default='legacy', help_text='SHA256 hash of paragraph content for deduplication', max_length=64),
            preserve_default=False,
        ),
    ]
