# Generated by Django 6.0 on 2025-12-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyllabusTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('keywords', models.TextField(help_text='Comma-separated keywords related to the topic')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
